# Generated by Django 4.0.1 on 2023-09-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='metadata',
            field=models.TextField(default=''),
        ),
    ]
