# Generated by Django 4.0.1 on 2023-09-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuesapp', '0002_user_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
